const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  openFile: () => ipcRenderer.invoke('open-file'),
  openSubtitle: () => ipcRenderer.invoke('open-subtitle'),
  readSubtitleFile: (path) => ipcRenderer.invoke('read-subtitle-file', path),
  saveSubtitleFile: (data) => ipcRenderer.invoke('save-subtitle-file', data),
  getFileDir: (path) => ipcRenderer.invoke('get-file-dir', path),
  getFileName: (path) => ipcRenderer.invoke('get-file-name', path),
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowMaximize: () => ipcRenderer.invoke('window-maximize'),
  windowClose: () => ipcRenderer.invoke('window-close'),
  windowFullscreen: () => ipcRenderer.invoke('window-fullscreen'),
  isFullscreen: () => ipcRenderer.invoke('is-fullscreen'),
  computeHash: (path) => ipcRenderer.invoke('compute-hash', path),
  searchSubtitlesOS: (data) => ipcRenderer.invoke('search-subtitles-opensubtitles', data),
  searchSubtitlesSubDB: (data) => ipcRenderer.invoke('search-subtitles-subdb', data),
  downloadSubtitleSubDB: (data) => ipcRenderer.invoke('download-subtitle-subdb', data),
  downloadSubtitle: (data) => ipcRenderer.invoke('download-subtitle', data),
  openFolder: () => ipcRenderer.invoke('open-folder'),
  listMediaFiles: (dir) => ipcRenderer.invoke('list-media-files', dir),
  saveSubtitleDownload: (data) => ipcRenderer.invoke('save-subtitle-download', data),
  pathExists: (p) => ipcRenderer.invoke('path-exists', p),
  onOpenPath: (cb) => ipcRenderer.on('open-path', (e, p) => cb(p)),
  grabberToolsAvailable: () => ipcRenderer.invoke('grabber-tools-available'),
  grabberDefaultDir: () => ipcRenderer.invoke('grabber-default-dir'),
  grabberChooseDir: () => ipcRenderer.invoke('grabber-choose-dir'),
  grabberOpenDir: (dir) => ipcRenderer.invoke('grabber-open-dir', dir),
  grabberStart: (data) => ipcRenderer.invoke('grabber-start', data),
  grabberCancel: (jobId) => ipcRenderer.invoke('grabber-cancel', jobId),
  onGrabberProgress: (cb) => ipcRenderer.on('grabber-progress', (e, d) => cb(d)),
  onGrabberDone: (cb) => ipcRenderer.on('grabber-done', (e, d) => cb(d)),
});
